# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 35
  - name: Videos
    url: videos/
    weight: 36
  - name: Gallery
    url: gallery/
    weight: 37
  - name: Links
    url: links/
    weight: 38
  - name: Books
    url: books/
    weight: 39
  - name: Prayers
    url: prayers/
    weight: 40
  - name: Contact
    url: contact/
    weight: 41
  - name: Catholic Life
    url: catholic_life/
    weight: 42
  - name: Donations
    url: donations/
    weight: 43